version: '3'

services:
  user.data:
    image: redis
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq
    
  webmvc:
    image: owaincharlon/m1cloud:web_m1cloud
    ports: 
    - 8080:80
    container_name: web
    depends_on:
      - applicants.api
      - identity.api
      - jobs.api
    restart: always

  applicants.api:
    image: owaincharlon/m1cloud:app_api_m1cloud
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;
      - HostRabbitmq=rabbitmq
    ports: 
    - 8081:80
    container_name: applicants.api
    depends_on:
      - sql.data
      - rabbitmq
    restart: always

  jobs.api:
    image: owaincharlon/m1cloud:jobs_api_m1cloud
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;
      - HostRabbitmq=rabbitmq 
    ports: 
    - 8083:80
    container_name: jobs.api
    depends_on:
      - sql.data
      - rabbitmq
    restart: always

  identity.api:
    image: owaincharlon/m1cloud:id_api_m1cloud
    environment:
      - RedisHost=user.data:6379
      - HostRabbitmq=rabbitmq
    ports: 
    - 8084:80
    container_name: identity.api
    depends_on:
      - user.data
      - rabbitmq       
    restart: always
  sql.data:
    image: mssql-linux
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - 1433:1433
    container_name: mssql-linux
